### PR TITLE
Add simple and list widgets

### PR DESCRIPTION
**Pull request by thardev**
So as I wrote some weeks ago on the issue #98 I finally got the time to finish the implementation. 
Hope everything is looking good for you, since I'm not that experienced on Android development there may be some refinement to be done :)
Thanks for your time and your work again 👍

### CODE REVIEW

**Comment by PhieF** [comment]
Arg I didn't get the notification ! I will try your pull request this weekend !

I was wondering if you did it ! Thank you very much !!

**Comment by thardev** [comment]
Sure, no problem 😄 we stay in contact for changes and comments and so on!

**Comment by PhieF** [comment]
I started looking at your work, this is great ! 
I will just avoid using getNotes and getNoteContent and try using methods I already wrote for browser / recent views !

Do you have any ideas how I could push to your push request to complete the code ?

Thanks !

**Comment by thardev** [comment]
Hey :)

I think you should be able to provide commits to my PR.
image

**Comment by PhieF** [comment]
This weekend I will try to add todolist support !

Thanks for your good work ! It works pretty well for now

On my side I'm now using the white icon for note creation, contrasts are better, what do you think ?
IMG_20210422_235811

**Comment by PhieF** [comment]
I guess I'm ready to merge !

**Comment by thardev** [comment]
It looks great :D thanks a lot for the changes and very happy that it will soon be released and working! :)

**Pull request merged**
